# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import py_shortcut
from py_shortcut.models.update_stories import UpdateStories  # noqa: E501
from py_shortcut.rest import ApiException


class TestUpdateStories(unittest.TestCase):
    """UpdateStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateStories(self):
        """Test UpdateStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_shortcut.models.update_stories.UpdateStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
