# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import py_shortcut
from py_shortcut.models.create_story_params import CreateStoryParams  # noqa: E501
from py_shortcut.rest import ApiException


class TestCreateStoryParams(unittest.TestCase):
    """CreateStoryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoryParams(self):
        """Test CreateStoryParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_shortcut.models.create_story_params.CreateStoryParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
