# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import py_shortcut
from py_shortcut.models.v3_files_body import V3FilesBody  # noqa: E501
from py_shortcut.rest import ApiException


class TestV3FilesBody(unittest.TestCase):
    """V3FilesBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV3FilesBody(self):
        """Test V3FilesBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_shortcut.models.v3_files_body.V3FilesBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
