# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_entity_template import CreateEntityTemplate  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateEntityTemplate(unittest.TestCase):
    """CreateEntityTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEntityTemplate(self):
        """Test CreateEntityTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_entity_template.CreateEntityTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
