# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_story_contents import UpdateStoryContents  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateStoryContents(unittest.TestCase):
    """UpdateStoryContents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateStoryContents(self):
        """Test UpdateStoryContents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_story_contents.UpdateStoryContents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
