# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import py_shortcut
from py_shortcut.models.update_linked_file import UpdateLinkedFile  # noqa: E501
from py_shortcut.rest import ApiException


class TestUpdateLinkedFile(unittest.TestCase):
    """UpdateLinkedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateLinkedFile(self):
        """Test UpdateLinkedFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_shortcut.models.update_linked_file.UpdateLinkedFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
