# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_api
from shortcut_api.models.create_story_link_params import CreateStoryLinkParams  # noqa: E501
from shortcut_api.rest import ApiException


class TestCreateStoryLinkParams(unittest.TestCase):
    """CreateStoryLinkParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoryLinkParams(self):
        """Test CreateStoryLinkParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shortcut_api.models.create_story_link_params.CreateStoryLinkParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
