# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.history_reference_story import HistoryReferenceStory  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryReferenceStory(unittest.TestCase):
    """HistoryReferenceStory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryReferenceStory(self):
        """Test HistoryReferenceStory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.history_reference_story.HistoryReferenceStory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
