# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.history_action_task_update import HistoryActionTaskUpdate  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryActionTaskUpdate(unittest.TestCase):
    """HistoryActionTaskUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryActionTaskUpdate(self):
        """Test HistoryActionTaskUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.history_action_task_update.HistoryActionTaskUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
