# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.history_action_project_update import HistoryActionProjectUpdate  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryActionProjectUpdate(unittest.TestCase):
    """HistoryActionProjectUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryActionProjectUpdate(self):
        """Test HistoryActionProjectUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.history_action_project_update.HistoryActionProjectUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
