# coding: utf-8

"""
    Shortcut API

    Shortcut API  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shortcut_api
from shortcut_api.models.list_group_stories import ListGroupStories  # noqa: E501
from shortcut_api.rest import ApiException


class TestListGroupStories(unittest.TestCase):
    """ListGroupStories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListGroupStories(self):
        """Test ListGroupStories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shortcut_api.models.list_group_stories.ListGroupStories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
